// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbwKq86V0vJg1i7IzB4q-bfIDsdHoBzL0',
    appId: '1:234882622946:web:81a2be55645e4f78e485bb',
    messagingSenderId: '234882622946',
    projectId: 'myapp-e2b02',
    authDomain: 'myapp-e2b02.firebaseapp.com',
    storageBucket: 'myapp-e2b02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWyvXlIZm6c5DlMKu1_SNX6tEOexi-STw',
    appId: '1:234882622946:android:b8edc555f0ff2ccbe485bb',
    messagingSenderId: '234882622946',
    projectId: 'myapp-e2b02',
    storageBucket: 'myapp-e2b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJ2TxsufAk55a8UTxOMkWmM1Lwtuga-w',
    appId: '1:234882622946:ios:2a33d5c44cec620fe485bb',
    messagingSenderId: '234882622946',
    projectId: 'myapp-e2b02',
    storageBucket: 'myapp-e2b02.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJ2TxsufAk55a8UTxOMkWmM1Lwtuga-w',
    appId: '1:234882622946:ios:2a33d5c44cec620fe485bb',
    messagingSenderId: '234882622946',
    projectId: 'myapp-e2b02',
    storageBucket: 'myapp-e2b02.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbwKq86V0vJg1i7IzB4q-bfIDsdHoBzL0',
    appId: '1:234882622946:web:8bf61f680a73171be485bb',
    messagingSenderId: '234882622946',
    projectId: 'myapp-e2b02',
    authDomain: 'myapp-e2b02.firebaseapp.com',
    storageBucket: 'myapp-e2b02.firebasestorage.app',
  );
}
